AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Template to create a DynamoDB table and an API for a todo list

Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: todo
      AttributeDefinitions:
        - AttributeName: todoId
          AttributeType: N
      KeySchema:
        - AttributeName: todoId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
    # TodoApi:
